#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'Pygments==0.11.1','console_scripts','pygmentize'
__requires__ = 'Pygments==0.11.1'
import sys
from pkg_resources import load_entry_point

sys.exit(
   load_entry_point('Pygments==0.11.1', 'console_scripts', 'pygmentize')()
)
