#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'Sphinx==0.4.3','console_scripts','sphinx-build'
__requires__ = 'Sphinx==0.4.3'
import sys
from pkg_resources import load_entry_point

sys.exit(
   load_entry_point('Sphinx==0.4.3', 'console_scripts', 'sphinx-build')()
)
